# Copyright 2020 the V8 project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: Deploy Modules Benchmark

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main Branch 
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build Jekyll Side
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Export Module Tree
        run: |
            mkdir _site/modules
            cp -r js _site/modules
            python3 ./gen.py --depth=5 --rules="A:ABCD" --sizes="A:1k,B:1k,C:1k,D:1k"
            mv out _site/modules/small-left
            python3 ./gen.py --depth=5 --rules="A:BCDA" --sizes="A:1k,B:1k,C:1k,D:1k"
            mv out _site/modules/small-right
            python3 ./gen.py --depth=3 --rules="A:BAC" --sizes="A:12k,B:1m,C:1k"
            mv out _site/modules/large

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
